name: Deploy a GitHub Pages

on:
  push:
    branches:
      - main  # Cambia 'main' si tu branch principal tiene otro nombre

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Permiso necesario para generar tokens de identidad
      contents: read    # Permiso para leer el contenido del repositorio
      pages: write      # Permiso para desplegar en GitHub Pages
    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v3

      - name: Crear config.js con Secrets
        run: |
          echo "export const HUEVA = \"${{ secrets.HUEVA }}\";" > variables.js

      - name: Subir artefacto para GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

      - name: Desplegar en GitHub Pages
        uses: actions/deploy-pages@v3

