name: Deploy a GitHub Pages

on:
  push:
    branches:
      - main  # Cambia 'main' si tu branch principal tiene otro nombre

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Permiso necesario para generar tokens de identidad
      contents: read    # Permiso para leer el contenido del repositorio
      pages: write      # Permiso para desplegar en GitHub 
    environment:  # Agrega el entorno aquí
      name: github-pages
    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v3

      - name: Crear config.js con Secrets
        run: |
          echo "export const HUEVA = \"${{ secrets.HUEVA }}\";" > variables.js

      - name: Listar archivos (para depuración)
        run: ls -R  # Lista todos los archivos para verificar que todo esté en su lugar

      - name: Subir artefacto para GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./  # Sube todos los archivos en la raíz del repositorio

      - name: Desplegar en GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment 